const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let batches=[],selected=null;
function toast(x){const d=document.createElement("div");d.textContent=x;d.style="position:fixed;right:20px;bottom:20px;background:#182236;color:#fff;padding:12px 15px;border-radius:9px;z-index:99";document.body.appendChild(d);setTimeout(()=>d.remove(),2800)}
function badge(s){const c=["TX_BUILT","DISPATCHED","SIGNED_OR_BROADCAST","EXECUTED","VALIDATED"].includes(s)?"ok":["VALIDATION_FAILED","TX_BUILD_FAILED","FAILED"].includes(s)?"bad":["PENDING","UNSIGNED"].includes(s)?"warn":"";return `<span class="badge ${c}">${esc(s)}</span>`}
async function refresh(){batches=await window.tronPC.listBatches();if(!selected||!batches.some(x=>x.id===selected))selected=batches[0]?.id||null;renderDash();renderSelect();renderReq();await renderOps()}
function renderDash(){const rs=batches.flatMap(x=>x.requests||[]);$("sb").textContent=batches.length;$("sr").textContent=rs.length;$("st").textContent=rs.filter(x=>x.tx).length;$("sd").textContent=rs.filter(x=>x.dispatch).length;$("dashTable").innerHTML=batches.length?`<table class="table"><tr><th>批次</th><th>网络</th><th>C</th><th>状态</th></tr>${batches.slice(0,12).map(b=>`<tr><td><b>${esc(b.name)}</b><br><small>${esc(b.id)}</small></td><td>${esc(b.network)}</td><td>${b.requests.length}</td><td>${badge(b.status)}</td></tr>`).join("")}</table>`:"暂无批次"}
function renderSelect(){const e=$("batchSel");e.innerHTML=batches.length?batches.map(b=>`<option value="${esc(b.id)}" ${b.id===selected?"selected":""}>${esc(b.name)} · ${b.requests.length} C</option>`).join(""):`<option>暂无批次</option>`}
function renderReq(){const b=batches.find(x=>x.id===selected);if(!b){$("reqTable").innerHTML="暂无";return}$("reqTable").innerHTML=`<table class="table"><tr><th>C</th><th>状态</th><th>Proposal</th><th>操作</th></tr>${b.requests.map(r=>`<tr><td><b>${esc(r.target)}</b><br><small>${esc(r.id)}</small></td><td>${badge(r.status)}${r.error?`<br>${esc(r.error)}`:""}</td><td class="mono">${esc(r.proposalHash)}</td><td>${r.tx?`<button class="secondary mini" onclick="dispatch('${r.id}','tronlink')">TronLink</button> <button class="secondary mini" onclick="dispatch('${r.id}','tokenpocket')">TP</button>`:"-"} <button class="secondary mini" onclick="detail('${r.id}')">详情</button></td></tr>`).join("")}</table>`}
window.detail=rid=>{const b=batches.find(x=>x.id===selected),r=b?.requests.find(x=>x.id===rid);if(!r)return;$("detail").classList.remove("hidden");$("detail").innerHTML=`<h2>请求详情</h2><div class="grid"><div><b>C</b><br>${esc(r.target)}</div><div><b>Request ID</b><br>${esc(r.id)}</div><div><b>A</b><br>${esc(b.aAddress)}</div><div><b>B</b><br>${esc(b.bAddress)}</div><div><b>Threshold</b><br>2 / 2</div><div><b>Proposal Hash</b><br><span class="mono">${esc(r.proposalHash)}</span></div></div>${r.tx?`<pre>${esc(JSON.stringify(r.tx,null,2))}</pre>`:""}${r.callback?`<pre>${esc(JSON.stringify(r.callback,null,2))}</pre>`:""}`}
window.dispatch=async(rid,w)=>{try{const x=await window.tronPC.deeplink(selected,rid,w);await navigator.clipboard?.writeText(x.url);await window.tronPC.open(x.url);await refresh();toast(w+" 请求已生成并尝试拉起钱包")}catch(e){toast(e.message||String(e))}}
$("batchSel").onchange=e=>{selected=e.target.value;renderReq()}
$("validate").onclick=async()=>{try{const x=await window.tronPC.validateBatch(selected,100);await refresh();toast(`验证完成：${x.filter(y=>y.ok).length}/${x.length}`)}catch(e){toast(e.message)}}
$("build").onclick=async()=>{try{const x=await window.tronPC.buildBatch(selected,100);await refresh();toast(`构建完成：${x.filter(y=>y.ok).length}/${x.length}`)}catch(e){toast(e.message)}}
$("exportBatch").onclick=async()=>{try{toast("已导出："+await window.tronPC.exportBatch(selected))}catch(e){toast(e.message)}}
$("create").onclick=async()=>{try{const hosts={mainnet:"https://api.trongrid.io",nile:"https://nile.trongrid.io",shasta:"https://api.shasta.trongrid.io"};await window.tronPC.setSettings({network:$("net").value,host:hosts[$("net").value],concurrency:Number($("conc").value),expiryMinutes:Number($("expiry").value)});const b=await window.tronPC.createBatch({name:$("name").value,aAddress:$("a").value,bAddress:$("b").value,expiryMinutes:Number($("expiry").value),addresses:$("cs").value.split(/[\\n,]+/).map(x=>x.trim()).filter(Boolean)});selected=b.id;await refresh();document.querySelector('[data-tab="requests"]').click();toast(`批次已创建：${b.requests.length} C`)}catch(e){toast(e.message)}}
$("fee").onclick=async()=>{$("feeout").textContent=JSON.stringify(await window.tronPC.chainParams(),null,2)}
$("opCreate").onclick=async()=>{try{const tx=JSON.parse($("opTx").value);const x=await window.tronPC.createOperation({from:$("opFrom").value,to:$("opTo").value,transaction:tx});await renderOps();toast("操作已保存："+x.id)}catch(e){toast(e.message)}}
$("opRefresh").onclick=renderOps;
async function renderOps(){const ops=await window.tronPC.listOperations();$("opTable").innerHTML=ops.length?`<table class="table"><tr><th>ID</th><th>From</th><th>Status</th><th>操作</th></tr>${ops.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.from||"")}</td><td>${badge(o.status)}</td><td><button class="secondary mini" onclick="sw('${o.id}')">检查 2/2</button> <button class="primary mini" onclick="bc('${o.id}')">广播</button></td></tr>`).join("")}</table>`:"暂无操作"}
window.sw=async id=>{try{const x=await window.tronPC.signWeight(id);await renderOps();toast(`当前权重：${x.current_weight||0}/2`)}catch(e){toast(e.message)}}
window.bc=async id=>{try{const x=await window.tronPC.broadcast(id);await renderOps();toast("广播："+JSON.stringify(x))}catch(e){toast(e.message)}}
$("save").onclick=async()=>{try{const x=await window.tronPC.setSettings({host:$("host").value,network:$("snet").value,callbackUrl:$("callback").value,callbackPort:Number($("port").value)});$("setout").textContent=JSON.stringify(x,null,2);toast("设置已保存")}catch(e){toast(e.message)}}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("on"));b.classList.add("on");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));$(b.dataset.tab).classList.add("on");$("title").textContent=b.textContent})
;(async()=>{const i=await window.tronPC.info(),s=await window.tronPC.getSettings();$("ready").textContent=`● Ready · v${i.version}`;$("network").textContent=s.network;$("host").value=s.host;$("snet").value=s.network;$("callback").value=s.callbackUrl;$("port").value=s.callbackPort;$("net").value=s.network;$("conc").value=s.concurrency;$("expiry").value=s.expiryMinutes;await refresh()})()
