const {contextBridge,ipcRenderer}=require("electron");
contextBridge.exposeInMainWorld("tronPC",{
  info:()=>ipcRenderer.invoke("info"),
  getSettings:()=>ipcRenderer.invoke("settings:get"),
  setSettings:p=>ipcRenderer.invoke("settings:set",p),
  chainParams:()=>ipcRenderer.invoke("chain:params"),
  account:a=>ipcRenderer.invoke("account:get",a),
  createBatch:x=>ipcRenderer.invoke("batch:create",x),
  listBatches:()=>ipcRenderer.invoke("batches:list"),
  validateBatch:(id,n)=>ipcRenderer.invoke("batch:validate",id,n),
  buildBatch:(id,n)=>ipcRenderer.invoke("batch:build",id,n),
  deeplink:(id,r,w)=>ipcRenderer.invoke("request:deeplink",id,r,w),
  open:u=>ipcRenderer.invoke("open",u),
  mark:(id,r,p)=>ipcRenderer.invoke("batch:mark",id,r,p),
  createOperation:x=>ipcRenderer.invoke("operation:create",x),
  listOperations:()=>ipcRenderer.invoke("operations:list"),
  signWeight:id=>ipcRenderer.invoke("operation:signweight",id),
  broadcast:id=>ipcRenderer.invoke("operation:broadcast",id),
  exportAudit:()=>ipcRenderer.invoke("audit:export"),
  exportBatch:id=>ipcRenderer.invoke("batch:export",id)
});
